package by.training.filmstore.controller;

public enum CommandName {
	CHANGE_LANGUAGE,
	SHOW_LIST_FILM,
	LOGINATION,
	LOGOUT,
	SIGN_UP,
	SIGN_UP_SHOW_PAGE, 
	LOGIN_SHOW_PAGE,
	INIT_POOL_CONNECTION, 
	DESTROY_POOL_CONNECTION, 
	SHOW_COMMENT_PAGE,
	MAKE_COMMENT,
	CREATE_FILM_SHOW_PAGE, 
	CREATE_FILM,
	UPDATE_FILM_SHOW_PAGE,
	ADMIN_FILMS_SHOW_PAGE
}
